### ISSUE TITLE
Corrección de MercadoLiebre :)

### ISSUE THREAD

**Issue by FernandoRafa2701** [Maxi20fi/mercadoLiebre#1]
Tiene la mayor parte de la estructura Felicidades.

Temas o contenido a mejorar:
-flexbox
-Agregar mas estilos CSS (para una mejor front-end)
-Completar los formularios de inicio y registro

Se puede te falta muy poco que mejorar tu pagina render ANIMOS ;)

**Comment by Maxi20fi** [comment]
Terminado...gracias por corregir
